services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME={USER_NAME}         # THIS IS TO BE REPLACED
      - DOCKER_INFLUXDB_INIT_PASSWORD={PASSWORD}          # THIS IS TO BE REPLACED
      - DOCKER_INFLUXDB_INIT_ORG=my-org                   # THIS CAN BE CHANGED
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf              # THIS CAN BE CHANGED
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-token   # THIS IS TO BE REPLACED

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER={GRAFANA_USER_NAME}         # THIS IS TO BE REPLACED
      - GF_SECURITY_ADMIN_PASSWORD={GRAFANA_PASSWORD}      # THIS IS TO BE REPLACED
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
